insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Burrowers, The', 1, 'Horror|Thriller|Western', 2011);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Samurai Spy (Ibun Sarutobi Sasuke)', 2, 'Action|Drama', 2013);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Prime Suspect', 3, 'Crime|Drama|Mystery|Thriller', 2003);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Atomic States of America, The', 4, 'Documentary', 2001);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Furry Vengeance', 5, 'Children|Comedy', 1986);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Great Expectations', 6, 'Drama', 2012);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Art of Getting By, The', 7, 'Drama|Romance', 1997);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Take a Giant Step', 8, 'Drama', 1994);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Labyrinth of Lies', 9, 'Drama', 1993);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Thomas in Love (Thomas est Amoureux)', 10, 'Comedy|Drama', 2000);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Frankie Starlight', 11, 'Drama|Romance', 2012);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Happily Ever After (Ils se marièrent et eurent beaucoup d''enfants)', 12, 'Comedy|Drama', 1994);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('The Thirteen Assassins', 13, 'Action|Adventure', 2001);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Behind Enemy Lines', 14, 'Action|Thriller', 2008);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Law and Order', 15, 'Action|Romance|Western', 1989);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Korengal', 16, 'Documentary|War', 1987);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Won Ton Ton: The Dog Who Saved Hollywood', 17, 'Comedy', 1990);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Connections', 18, 'Documentary', 1992);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Twogether', 19, 'Comedy|Drama', 1955);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Gentle Woman, A (Une femme douce)', 20, 'Drama', 2006);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Bio Zombie (Sun faa sau si)', 21, 'Comedy|Horror', 2002);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Patriot, The', 22, 'Action|Thriller', 1992);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Dogma', 23, 'Adventure|Comedy|Fantasy', 2010);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Journey Into Fear', 24, 'Drama|Film-Noir|War', 2007);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Afternoon of a Torturer, The (Dupa-amiaza unui tortionar)', 25, 'Drama', 2000);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Paulie', 26, 'Adventure|Children|Comedy', 2002);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Patriots, The (Patriotes, Les)', 27, 'Thriller', 2000);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Video Games: The Movie', 28, 'Documentary', 1991);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('X-Files: Fight the Future, The', 29, 'Action|Crime|Mystery|Sci-Fi|Thriller', 1987);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Stray Dogs', 30, 'Drama', 1997);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Child, The', 31, 'Thriller', 2009);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Dr. Dolittle', 32, 'Comedy', 2005);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Wind Chill', 33, 'Drama|Horror|Thriller', 1990);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Outrage (Autoreiji)', 34, 'Crime|Drama', 2002);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Lemmy', 35, 'Documentary', 2006);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Guns of the Magnificent Seven', 36, 'Action|Adventure|Drama|Western', 2005);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('The Opposite Sex', 37, 'Comedy|Drama|Romance', 2004);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Bronies: The Extremely Unexpected Adult Fans of My Little Pony', 38, 'Documentary', 1996);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Breakaway (Speedy Singhs)', 39, 'Comedy|Drama', 2011);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Ring Finger, The (L''annulaire)', 40, 'Drama', 1981);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Kiss Me, Stupid', 41, 'Comedy', 1993);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Weeds', 42, 'Drama', 2000);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Friday the 13th Part VIII: Jason Takes Manhattan', 43, 'Horror', 1998);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Crazy Beautiful You', 44, '(no genres listed)', 1990);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Anna', 45, 'Drama', 2012);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Sleep Dealer', 46, 'Sci-Fi', 1999);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Rabbit-Proof Fence', 47, 'Adventure|Drama', 2000);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('If Looks Could Kill', 48, 'Action|Comedy', 2000);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Prince of the City', 49, 'Drama', 2013);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Gunfighter''s Moon', 50, 'Romance|Western', 1997);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('24 Hour Party People', 51, 'Comedy|Drama|Musical', 1986);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Four Nights with Anna (Cztery noce z Anna)', 52, 'Crime|Drama|Thriller', 1993);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Strangeland', 53, 'Thriller', 2000);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Marc Pease Experience, The', 54, 'Comedy|Drama|Musical', 2002);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Bull Durham', 55, 'Comedy|Drama|Romance', 2007);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Rambo: First Blood Part II', 56, 'Action|Adventure|Thriller', 2003);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Gilles'' Wife (La femme de Gilles)', 57, 'Drama', 1998);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Experiment Perilous', 58, 'Romance|Thriller', 2005);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Scorpion King 3: Battle for Redemption, The', 59, 'Action|Adventure|Comedy|Fantasy', 1991);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Miranda', 60, 'Comedy|Fantasy|Romance', 1986);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Princess and the Frog, The', 61, 'Animation|Children|Fantasy|Musical|Romance', 1993);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('La Luna', 62, 'Animation', 1998);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Savage Nights (Nuits fauves, Les)', 63, 'Drama', 2003);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Higher Learning', 64, 'Drama', 2007);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Voices of a Distant Star (Hoshi no koe)', 65, 'Animation|Drama|Romance|Sci-Fi', 2011);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Rage: Carrie 2, The', 66, 'Horror', 2010);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Man Behind the Gun, The', 67, 'Western', 2010);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Egyptian, The', 68, 'Drama', 2000);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Jay and Silent Bob Strike Back', 69, 'Adventure|Comedy', 1993);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Story of Temple Drake, The', 70, 'Drama', 2005);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Archangel', 71, 'Comedy', 1990);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Man''s Best Friend', 72, 'Horror|Sci-Fi|Thriller', 1994);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Our Fathers', 73, 'Drama', 2010);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Haunting, The', 74, 'Horror|Thriller', 2008);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Our Daily Bread (Unser täglich Brot)', 75, 'Documentary', 2005);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Demonic', 76, 'Horror|Thriller', 2000);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Ganes', 77, 'Drama|Musical', 1967);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('What A Man', 78, 'Comedy|Romance', 2012);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Hit Lady', 79, 'Crime|Drama|Thriller', 2004);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Teacher''s Pet', 80, 'Animation|Children', 2006);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Beauty of the Day (Belle de jour)', 81, 'Drama', 1971);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('They Call Me Bruce? (a.k.a. A Fistful of Chopsticks)', 82, 'Comedy', 1991);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Some Kind of Hero', 83, 'Comedy|Drama', 2005);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Lost World: Jurassic Park, The', 84, 'Action|Adventure|Sci-Fi|Thriller', 1967);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('St. Vincent', 85, 'Comedy', 2001);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Corporation, The', 86, 'Documentary', 1994);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Carlito''s Way: Rise to Power (Carlito''s Way 2: Rise to Power)', 87, 'Action|Crime|Drama|Thriller', 2004);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Of Time and the City', 88, 'Documentary', 1994);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Virunga', 89, 'Documentary|War', 2003);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Pushing Tin', 90, 'Comedy', 1997);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Different for Girls', 91, 'Comedy', 2009);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Link', 92, 'Horror|Thriller', 1995);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Amongst Friends', 93, 'Crime|Drama', 2010);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Largo Winch (Heir Apparent: Largo Winch, The)', 94, 'Adventure|Thriller', 2009);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Room 237', 95, 'Documentary', 1993);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Blue Chips', 96, 'Drama', 2005);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Charm School (Niñas mal)', 97, 'Comedy', 2002);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Season for Miracles, A', 98, 'Children|Romance', 1989);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Hell''s Kitchen', 99, 'Drama', 2001);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Asterix & Obelix: God Save Britannia (Astérix et Obélix: Au service de Sa Majesté)', 100, 'Adventure|Comedy', 2010);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Someone I Loved (Je l''aimais)', 101, 'Drama|Romance', 2012);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Conception', 102, 'Comedy|Romance', 2004);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Exit to Hell', 103, 'Action|Horror|Thriller', 1992);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Legend of the 7 Golden Vampires, The', 104, 'Action|Horror', 2005);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Upstream Color', 105, 'Romance|Sci-Fi|Thriller', 1998);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Ghoulies III: Ghoulies Go to College', 106, 'Comedy|Horror', 2002);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Female Agents (Les femmes de l''ombre)', 107, 'Drama|War', 2001);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('What to Do in Case of Fire (Was tun, wenn''s brennt?)', 108, 'Comedy|Drama', 2009);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Daybreakers', 109, 'Action|Drama|Horror|Thriller', 2012);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Commandments', 110, 'Romance', 2006);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Looking for Lenny ', 111, 'Documentary', 1996);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Dallas 362', 112, 'Drama', 2013);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Cleopatra', 113, 'Comedy|Drama', 2000);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Swann in Love (Un amour de Swann)', 114, 'Drama', 2001);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Adventures of Tintin, The', 115, 'Action|Animation|Mystery|IMAX', 2010);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Drop Zone', 116, 'Action|Thriller', 2004);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Hostel: Part II', 117, 'Crime|Horror|Thriller', 1996);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Warped Ones, The (Kyonetsu no kisetsu)', 118, 'Drama', 1969);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Smiley''s People', 119, 'Drama|Mystery', 1990);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Close Your Eyes (Hypnotic) (Doctor Sleep)', 120, 'Crime|Thriller', 2011);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Stricken (Er komt een vrouw bij de dokter)', 121, 'Drama|Romance', 2010);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('American Ninja 5', 122, 'Action', 2004);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Lethal Weapon', 123, 'Action|Comedy|Crime|Drama', 2010);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('French Kiss', 124, 'Action|Comedy|Romance', 2005);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Ten Commandments, The', 125, 'Drama', 1992);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Murder in Greenwich', 126, 'Crime|Drama|Mystery', 1988);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Breathing Fire', 127, 'Action', 2010);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Creature Comforts', 128, 'Animation|Comedy', 1997);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Brain Smasher... A Love Story (Bouncer and the Lady, The)', 129, 'Action|Comedy', 2011);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Whistle Down the Wind', 130, 'Drama', 2004);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('The Bloodstained Butterfly', 131, 'Mystery|Thriller', 1998);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Carousel', 132, 'Musical|Romance', 1996);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Pumpkin', 133, 'Comedy|Drama|Romance', 2008);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Three Guys Named Mike', 134, 'Comedy|Romance', 1997);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Mountain, The', 135, 'Adventure|Drama', 1995);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Barefoot Gen (Hadashi no Gen)', 136, 'Animation|Drama|War', 1985);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('The Odyssey', 137, 'Adventure|Drama|Fantasy', 2004);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Romancing the Stone', 138, 'Action|Adventure|Comedy|Romance', 2007);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Housefull 2', 139, 'Comedy|Romance', 2008);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Beverly Hills Cop', 140, 'Action|Comedy|Crime|Drama', 2008);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Unholy Wife, The', 141, 'Crime|Drama', 1993);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Arrow, The', 142, 'Drama', 1990);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Dark Ride', 143, 'Horror|Thriller', 2003);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('On the Threshold (Lars i porten)', 144, 'Children|Drama', 2004);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Strong Man, The', 145, 'Comedy', 2002);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('In the Army Now', 146, 'Comedy|War', 2012);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Grave Encounters 2', 147, 'Horror', 1997);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Music and Lyrics', 148, 'Comedy|Romance', 1987);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('North to Alaska', 149, 'Comedy|Western', 1996);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('To Rome with Love', 150, 'Comedy', 1999);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Sällskapsresan II - Snowroller', 151, 'Comedy', 1995);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('High Crimes', 152, 'Thriller', 2012);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Adrenaline Drive (Adorenarin doraibu)', 153, 'Comedy', 1993);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Comme un chef', 154, 'Comedy', 2013);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Richard III', 155, 'Drama|War', 2008);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Chiko', 156, 'Crime|Drama', 2010);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Viva Las Vegas', 157, 'Comedy|Musical|Romance', 1994);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Bullet to the Head', 158, 'Action|Crime|Film-Noir', 2008);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Mayor of the Sunset Strip', 159, 'Documentary', 1966);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Bootmen', 160, 'Comedy|Drama', 1998);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('What Doesn''t Kill You', 161, 'Crime|Drama', 2004);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Pier, The (Jetée, La)', 162, 'Romance|Sci-Fi', 1992);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Outlander', 163, 'Action|Adventure|Sci-Fi', 2009);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Eleventh Year, The (Odinnadtsatyy) ', 164, 'Documentary', 1996);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Dead Poets Society', 165, 'Drama', 1997);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Lost and Found', 166, '(no genres listed)', 2009);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Tinker, Tailor, Soldier, Spy', 167, 'Drama|Thriller', 1999);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Pippi on the Run (På rymmen med Pippi Långstrump)', 168, 'Children', 1999);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('London to Brighton', 169, 'Crime|Drama|Thriller', 1998);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Scooby-Doo! WrestleMania Mystery', 170, 'Animation|Children', 1990);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('No Greater Love', 171, 'Drama|Romance', 2010);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Trio, The (Trio, Das)', 172, 'Drama|Romance', 1995);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Reform School Girls', 173, 'Action|Drama', 2006);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Firelight', 174, 'Drama', 1989);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Because of Winn-Dixie', 175, 'Children|Comedy|Drama', 1997);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Outside the Law', 176, 'Action', 2003);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Triumph of the Spirit', 177, 'Drama', 1992);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Dark Woods (Villmark)', 178, 'Adventure|Horror|Mystery|Thriller', 1992);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Hôtel des Invalides', 179, 'Documentary', 1990);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Yanks', 180, 'Drama|Romance|War', 2000);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('King''s Faith', 181, 'Drama', 1994);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Star Trek II: The Wrath of Khan', 182, 'Action|Adventure|Sci-Fi|Thriller', 1998);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Ito: A Diary of an Urban Priest (Seitti - kilvoittelijan päiväkirja)', 183, 'Documentary', 2001);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Extract', 184, 'Comedy', 2000);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Mademoiselle Chambon', 185, 'Drama|Romance', 1989);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('When Trumpets Fade', 186, 'Drama|War', 1986);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Safe Men', 187, 'Comedy', 2003);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Bachelor Night', 188, 'Comedy', 2003);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Peach Thief, The (Kradetzat na praskovi)', 189, 'Drama|Romance|War', 1995);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Zelig', 190, 'Comedy', 2009);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('I Know Where I''m Going!', 191, 'Drama|Romance|War', 2010);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Punks', 192, 'Comedy', 1983);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Speed', 193, 'Action|Romance|Thriller', 1996);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Flowers of War, The (Jin líng shí san chai)', 194, 'Drama|War', 1986);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Flicka', 195, 'Children|Drama', 1985);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Strange Days', 196, 'Action|Crime|Drama|Mystery|Sci-Fi|Thriller', 2001);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Madame Sousatzka', 197, 'Drama', 2002);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('My Wife''s Relations', 198, 'Comedy', 2009);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Madeinusa', 199, 'Drama', 1997);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Boy', 200, 'Comedy|Drama', 2010);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Jim Gaffigan: Mr. Universe', 201, 'Comedy', 2007);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Cat''s-Paw, The', 202, 'Comedy', 2009);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Predator 2', 203, 'Action|Sci-Fi|Thriller', 2006);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Triage', 204, 'Drama|War', 2012);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Across the Line: The Exodus of Charlie Wright', 205, 'Crime|Drama', 1997);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Last Sunset, The', 206, 'Western', 1965);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Good Earth, The', 207, 'Drama', 2004);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Seven Little Foys, The', 208, 'Comedy|Drama', 2004);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Hasty Heart, The', 209, 'Drama', 2001);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Rain Man', 210, 'Drama', 1967);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Cat and the Canary, The', 211, 'Comedy|Horror|Mystery', 2012);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Clownhouse', 212, 'Horror', 2012);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Prizefighter and the Lady, The', 213, 'Comedy|Crime|Romance', 2011);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Quinceañera', 214, 'Drama', 2010);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('New Jack City', 215, 'Action|Crime|Drama', 1996);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Road to Brown, The', 216, 'Documentary', 2000);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Shrek the Third', 217, 'Adventure|Animation|Children|Comedy|Fantasy', 2007);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Three Days of the Condor (3 Days of the Condor)', 218, 'Drama|Mystery|Romance|Thriller', 2008);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Company Business', 219, 'Action|Comedy', 2009);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Blue Angel, The (Blaue Engel, Der)', 220, 'Drama', 2007);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Closure', 221, 'Documentary', 2003);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Hacks (Sink or Swim) (Big Twist, The)', 222, 'Comedy|Mystery', 1994);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Jack Brooks: Monster Slayer', 223, 'Action|Comedy|Horror', 2006);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('White Balloon, The (Badkonake sefid)', 224, 'Children|Drama', 2001);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Carrie', 225, 'Drama|Horror|Thriller', 2000);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Gasoline (Benzina)', 226, 'Crime', 1993);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Marathon Family, The (Maratonci Trce Pocasni Krug)', 227, 'Comedy', 2004);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Death in Venice (Morte a Venezia)', 228, 'Drama|Romance', 2011);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Ewok Adventure, The (a.k.a. Caravan of Courage: An Ewok Adventure)', 229, 'Adventure|Children|Fantasy|Sci-Fi', 2006);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Steamboy (Suchîmubôi)', 230, 'Action|Animation|Drama|Sci-Fi', 2001);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Take Care of My Cat (Goyangileul butaghae)', 231, 'Drama', 2010);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Paralyzing Fear: The Story of Polio in America, A', 232, 'Documentary', 2005);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Mysterious Lady, The', 233, 'Drama|Romance', 1995);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Hiroshima', 234, 'Comedy', 1990);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Tai Chi Zero', 235, 'Action|Fantasy|Sci-Fi|IMAX', 1995);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('All About Lola (Ce que je sais de Lola) (Lo que sé de Lola)', 236, 'Romance', 1993);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Generation P', 237, 'Comedy|Drama|Sci-Fi', 2006);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Lusty Men, The', 238, 'Action|Drama|Western', 2006);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Soulless', 239, 'Comedy|Drama', 2006);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('First Family', 240, 'Comedy', 2001);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Transformers: Age of Extinction', 241, 'Action|Adventure|Sci-Fi', 2006);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Ben X', 242, 'Drama', 2010);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Blue Hawaii', 243, 'Comedy|Musical', 1991);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Nine Ways to Approach Helsinki (Yhdeksän tapaa lähestyä Helsinkiä)', 244, 'Documentary', 1988);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Shag', 245, 'Comedy|Drama', 1995);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Mighty Wind, A', 246, 'Comedy|Musical', 2006);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Raise Your Voice', 247, 'Romance', 2004);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Mating Game, The', 248, 'Comedy|Romance', 1999);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Prisoner of Zenda, The', 249, 'Adventure', 1995);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Edward Scissorhands', 250, 'Drama|Fantasy|Romance', 2003);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Tamara', 251, 'Fantasy|Horror|Thriller', 1995);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Jimi Hendrix: Hear My Train A Comin''', 252, 'Documentary', 2004);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Revenge of the Nerds', 253, 'Comedy', 2001);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('I Bury the Living', 254, 'Horror', 1996);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('So Young (Zhi wo men zhong jiang shi qu de qing chun)', 255, 'Drama', 2011);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Children of the Damned', 256, 'Horror|Sci-Fi|Thriller', 1998);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Inspector Gadget', 257, 'Action|Adventure|Children|Comedy', 1995);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Pieta', 258, 'Drama', 2000);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Downfall (Untergang, Der)', 259, 'Drama|War', 2006);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Wall Street: Money Never Sleeps', 260, 'Drama', 2003);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Dances With the Dragons ( Yu long gong wu)', 261, 'Comedy|Drama|Romance', 2007);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Amour fou, L''', 262, 'Documentary', 1992);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Dark Skies', 263, 'Horror|Sci-Fi|Thriller', 1995);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Invisible War, The', 264, 'Crime|Documentary|Drama|War', 2003);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('BFFs', 265, 'Comedy', 2007);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Pandorum', 266, 'Horror|Sci-Fi|Thriller', 2007);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Aningaaq', 267, 'Drama', 1987);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Inheritors, The (Siebtelbauern, Die)', 268, 'Drama|Mystery', 1992);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Method to the Madness of Jerry Lewis', 269, 'Documentary', 2006);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Captive Women (1000 Years from Now) (3000 A.D.)', 270, 'Sci-Fi', 2008);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Boris Godunov', 271, 'Drama', 2008);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('North West Mounted Police', 272, 'Action|Adventure|Drama|Romance|Western', 2005);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Paradise: Love', 273, 'Drama', 2012);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Paid', 274, 'Crime|Drama|Film-Noir', 2003);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Walk Hard: The Dewey Cox Story', 275, 'Comedy|Musical', 1999);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Robin Hood', 276, 'Action|Adventure|Drama|Romance|War', 2000);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Brady Bunch Movie, The', 277, 'Comedy', 2008);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Disfigured', 278, 'Drama', 1995);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Bosko''s Parlor Pranks', 279, 'Animation', 2007);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Emergo (Apartment 143)', 280, 'Horror', 1990);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Crying Out Love in the Center of the World (Sekai no chûshin de, ai o sakebu)', 281, 'Drama|Romance', 1991);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Missing, The', 282, 'Adventure|Thriller|Western', 2009);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('I Love You, I Love You (Je t''aime je t''aime)', 283, 'Drama|Sci-Fi', 2010);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('April Story', 284, 'Romance', 1990);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Green Lantern: First Flight', 285, 'Action|Adventure|Animation|Fantasy|Sci-Fi', 2010);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Je suis né d''une cigogne', 286, 'Comedy|Fantasy', 2004);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Des roses en hiver', 287, 'Drama', 2009);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Experiment in Terror', 288, 'Crime|Thriller', 2001);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Angel of Mine (a.k.a. The Mark of an Angel) (L''empreinte de l''ange)', 289, 'Drama', 2006);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Hideous Sun Demon, The', 290, 'Horror|Sci-Fi', 1993);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Couples Retreat', 291, 'Comedy|Romance', 1999);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Ring of Darkness', 292, 'Horror|Thriller', 1994);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Sallah', 293, 'Comedy', 2001);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Gorko!', 294, 'Comedy', 1995);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('The Student', 295, 'Comedy|Romance', 2012);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('White Sheik, The (Sceicco bianco, Lo)', 296, 'Comedy|Romance', 2007);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('About Elly (Darbareye Elly)', 297, 'Drama|Mystery', 2007);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Crawling Hand, The', 298, 'Horror|Sci-Fi', 2009);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Missing in Action 2: The Beginning', 299, 'Action|War', 2006);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('The Little Polar Bear: Lars and the Little Tiger', 300, 'Animation|Children', 2004);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Fort Bliss', 301, 'Drama|War', 1997);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Age of the Dragons', 302, 'Action|Adventure|Fantasy', 1996);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Bubble Boy', 303, 'Comedy', 2010);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Forrest Gump', 304, 'Comedy|Drama|Romance|War', 1997);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Galaxy of Terror (Quest)', 305, 'Action|Horror|Mystery|Sci-Fi', 1991);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Public Housing', 306, 'Documentary', 1997);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Tom and Jerry: The Movie', 307, 'Animation|Children|Comedy', 2002);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Smoking/No Smoking', 308, 'Comedy', 2009);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Here Comes the Boom', 309, 'Action|Comedy', 1998);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Debt, The', 310, 'Thriller', 2003);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Take the Money and Run', 311, 'Comedy|Crime', 2009);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Versailles', 312, 'Drama', 2009);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Silent Movie', 313, 'Comedy', 1995);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Three Musketeers, The', 314, 'Action|Adventure|Comedy', 1986);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Between Two Worlds', 315, 'Action|Adventure|Drama|Fantasy|Mystery', 2003);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Death at a Funeral', 316, 'Comedy', 1971);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Room at the Top', 317, 'Drama', 2005);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Dead of Night', 318, 'Horror|Mystery', 2002);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Another You', 319, 'Comedy', 2003);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Wedding Night, The', 320, 'Drama|Romance', 1989);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Apartment for Peggy', 321, 'Drama', 2006);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Caiman, The (Il caimano)', 322, 'Comedy|Drama|Romance', 2011);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Elevator', 323, 'Comedy|Drama', 1990);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Coffin Rock', 324, 'Thriller', 1998);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Diary of a Nymphomaniac (Diario de una Ninfómana)', 325, 'Drama', 2003);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Man of the World', 326, 'Drama|Romance', 1998);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Kings of Mykonos, The', 327, 'Comedy', 1997);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Half Past Dead', 328, 'Action|Crime|Thriller', 1990);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Opportunists, The', 329, 'Comedy|Crime|Drama', 2008);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Cab for Three, A (Taxi para tres)', 330, 'Action|Comedy|Crime|Drama', 1996);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Viva Max!', 331, '(no genres listed)', 2009);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Money for Nothing', 332, 'Comedy|Crime', 2000);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Librarian: Quest for the Spear, The', 333, 'Action|Adventure|Comedy|Fantasy|Romance', 1986);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('It''s Impossible to Learn to Plow by Reading Books', 334, 'Drama', 1994);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('That Uncertain Feeling', 335, 'Comedy', 2007);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Hypothesis of the Stolen Painting, The (L''hypothèse du tableau volé)', 336, 'Drama|Mystery', 1995);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Trespass', 337, 'Action|Crime|Thriller', 2000);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Stormbreaker (Alex Rider: Operation Stormbreaker)', 338, 'Action|Children', 2008);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Kidnapping of the President, The', 339, 'Action|Drama|Thriller', 2003);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Loves of Pharaoh, The (Das Weib des Pharao)', 340, 'Drama|Romance|War', 1996);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Keoma', 341, 'Action|Drama|Western', 2002);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Ultramarathon Man: 50 Marathons, 50 States, 50 Days', 342, 'Documentary', 2005);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Supercop (Police Story 3: Supercop) (Jing cha gu shi III: Chao ji jing cha)', 343, 'Action|Comedy|Crime|Thriller', 2008);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Wendigo', 344, 'Drama|Horror', 1999);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('One A.M.', 345, 'Comedy', 1957);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Horde, The (La Horde)', 346, 'Action|Horror|Thriller', 2005);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Prinsessa (Starring Maja)', 347, 'Drama', 2010);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Docking the Boat (Att angöra en brygga)', 348, 'Comedy|Drama|Romance', 2002);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Mac and Me', 349, 'Children|Fantasy|Sci-Fi', 2004);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Nude Bomb, The', 350, 'Comedy', 1988);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Biggles', 351, 'Adventure|Fantasy|Sci-Fi', 2002);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Werewolf of London', 352, 'Drama|Fantasy|Horror|Sci-Fi', 2010);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Blink', 353, 'Thriller', 2008);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Alien Nation', 354, 'Crime|Drama|Sci-Fi|Thriller', 1997);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('12th & Delaware', 355, 'Documentary', 2000);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Hotel', 356, 'Comedy', 2013);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Alexandria... Why? (Iskanderija... lih?)', 357, 'Drama', 1998);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Tinker, Tailor, Soldier, Spy', 358, 'Drama|Thriller', 1999);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Nazis Strike, The (Why We Fight, 2)', 359, 'Documentary|War', 2000);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Seven Up!', 360, 'Documentary', 1989);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('7 Below (Seven Below)', 361, 'Horror|Thriller', 2009);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Vic+Flo Saw a Bear', 362, 'Crime|Drama|Thriller', 2002);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Romanzo Criminale', 363, 'Crime|Drama', 2000);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Trial and Error', 364, 'Comedy|Romance', 1999);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('S.O.S. Eisberg', 365, 'Adventure|Drama', 1994);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Love (Szerelem)', 366, 'Drama', 2007);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Cotton Comes to Harlem', 367, 'Action|Comedy', 1996);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('How the Grinch Stole Christmas!', 368, 'Animation|Comedy|Fantasy|Musical', 2000);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Separate Tables', 369, 'Drama', 2007);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Contract, The', 370, 'Crime|Drama|Thriller', 2006);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Smilin'' Through', 371, 'Drama|Romance', 2002);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Diving Bell and the Butterfly, The (Scaphandre et le papillon, Le)', 372, 'Drama', 2011);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Machine Gun Kelly', 373, 'Action|Crime', 1996);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('One Day', 374, 'Drama|Romance', 2008);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Serious Man, A', 375, 'Comedy|Drama', 2011);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Sunshine', 376, 'Adventure|Drama|Sci-Fi|Thriller', 1985);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('For a Few Dollars More (Per qualche dollaro in più)', 377, 'Action|Drama|Thriller|Western', 1993);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Gentlemen', 378, 'Drama|Romance|Thriller', 2002);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Vesna va veloce', 379, 'Drama', 1995);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Wanted', 380, 'Action|Romance', 1991);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Bruna Surfistinha', 381, 'Drama', 2006);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Sons of the Desert', 382, 'Comedy', 2011);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('King Solomon''s Mines', 383, 'Adventure|Comedy', 2009);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Peyton Place', 384, 'Drama|Romance', 1999);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Honeymoon Killers, The', 385, 'Crime|Thriller', 1994);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Our Little Girl', 386, 'Comedy|Drama|Romance', 2006);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Forbidden Zone', 387, 'Musical|Sci-Fi', 1998);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Kids in the Hall: Same Guys, New Dresses', 388, 'Comedy|Documentary', 2007);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Across 110th Street', 389, 'Crime', 2007);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Trials of Henry Kissinger, The', 390, 'Documentary', 1964);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Heiter bis wolkig', 391, 'Comedy|Drama|Romance', 2002);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Carnival in Flanders (La kermesse héroïque)', 392, 'Comedy|Romance', 2008);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Jamie and Jessie Are Not Together', 393, 'Comedy|Musical|Romance', 1998);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Booker''s Place: A Mississippi Story', 394, 'Documentary|Mystery', 2003);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('I Accuse', 395, 'Drama|Horror|Sci-Fi|War', 2012);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Crisis: Behind a Presidential Commitment', 396, 'Documentary', 2010);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Greatest Story Ever Told, The', 397, 'Drama', 1996);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Bill Burr: You People Are All the Same', 398, 'Comedy', 2001);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Hannie Caulder', 399, 'Comedy|Crime|Drama|Western', 2011);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('True Believer', 400, 'Crime', 2008);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Mudhoney', 401, 'Drama', 1993);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Highwaymen', 402, 'Action|Crime|Thriller', 2003);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Spirit of ''76, The', 403, 'Comedy|Sci-Fi', 2002);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Swept from the Sea', 404, 'Drama|Romance', 2001);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Soft Skin, The (La peau douce)', 405, 'Drama', 1993);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Shara (Sharasojyu)', 406, 'Drama', 2012);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Mr. Untouchable', 407, 'Crime|Documentary', 2009);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('10.000 Km (Long Distance)', 408, 'Drama|Romance', 2010);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Ditchdigger''s Daughters, The', 409, 'Drama', 2003);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Breaker! Breaker!', 410, 'Action|Adventure|Crime', 1989);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Girl Walks Into a Bar', 411, 'Comedy|Drama|Fantasy', 2006);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('The Squeeze', 412, 'Action|Comedy|Crime|Romance|Thriller', 2005);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Music From Another Room', 413, 'Drama|Romance', 2008);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Chasing Papi (a.k.a. Papi Chulo)', 414, 'Comedy', 2004);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Great Passage, The (Fune wo amu)', 415, 'Drama', 2008);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Von Ryan''s Express', 416, 'Action|Adventure|Drama|War', 1986);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Three Musketeers, The', 417, 'Action|Adventure|Comedy|Romance', 1999);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Good Bye (Bé omid é didar)', 418, 'Drama', 1995);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('2081', 419, 'Action|Sci-Fi', 1993);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('It Follows', 420, 'Horror', 2005);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Swedish Love Story, A (Kärlekshistoria, En)', 421, 'Drama|Romance', 2008);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Chess Players, The (Shatranj Ke Khilari)', 422, 'Comedy|Drama', 1993);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Devil Doll, The', 423, 'Horror|Sci-Fi', 1994);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Chasing Liberty', 424, 'Comedy|Romance', 2010);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Chasers', 425, 'Comedy', 1994);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Oz the Great and Powerful', 426, 'Action|Adventure|Fantasy|IMAX', 2000);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Aftershock', 427, 'Horror|Thriller', 2010);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Somewhere in Time', 428, 'Drama|Romance', 1995);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('His New Profession', 429, 'Comedy', 2008);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('No Man''s Land', 430, 'Drama|War', 2000);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Stella Dallas', 431, 'Drama', 1995);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Price of Milk, The', 432, 'Comedy|Drama|Fantasy|Romance', 2012);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('South Pacific', 433, 'Musical|Romance|War', 1999);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Tito and Me (Tito i ja)', 434, 'Comedy', 2002);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Girl with the Red Scarf, The (Selvi boylum, al yazmalim)', 435, 'Drama|Romance', 1989);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('To Rome with Love', 436, 'Comedy', 2005);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Beekeeper, The (O melissokomos)', 437, 'Drama', 2012);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Animal Love (Tierische Liebe)', 438, 'Documentary', 2006);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Employees Leaving the Lumière Factory', 439, 'Documentary', 1995);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Smiley', 440, 'Horror', 2006);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Strip Search', 441, 'Drama', 2007);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Marooned', 442, 'Drama|Sci-Fi', 1993);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('I Killed My Mother (J''ai tué ma mère)', 443, 'Drama', 2006);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('The Facility', 444, 'Horror|Sci-Fi', 2000);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('State Fair', 445, 'Comedy|Drama|Romance', 1994);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Model Shop', 446, 'Drama', 2005);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Last Castle, The', 447, 'Action', 1995);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Rumble Fish', 448, 'Drama', 2008);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Leif', 449, 'Comedy|Musical', 2010);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Stranger on the Prowl (Imbarco a mezzanotte)', 450, 'Drama', 1998);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Lucky Break', 451, 'Comedy|Crime', 2001);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Mission Congo', 452, 'Documentary', 2009);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Look', 453, 'Drama', 1999);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Running Time', 454, 'Crime|Thriller', 2010);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Ice Rink, The (La patinoire)', 455, 'Comedy|Romance', 1996);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Mind Reader, The', 456, 'Drama|Romance', 1995);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('High Fidelity', 457, 'Comedy|Drama|Romance', 1992);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Josh and S.A.M.', 458, 'Adventure|Comedy|Drama', 1991);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Grindhouse', 459, 'Action|Crime|Horror|Sci-Fi|Thriller', 1999);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Lady in a Cage', 460, 'Drama|Thriller', 2010);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Summer Magic', 461, 'Children|Comedy|Musical', 1998);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Being Elmo: A Puppeteer''s Journey', 462, 'Documentary', 1993);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Real Fiction (Shilje sanghwang)', 463, 'Crime|Drama', 2010);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Junebug', 464, 'Comedy|Drama', 2000);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Gertie the Dinosaur', 465, 'Animation|Children|Comedy', 2002);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Scorpion King 2: Rise of a Warrior, The', 466, 'Action|Adventure|Fantasy', 1995);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Teenage Dirtbag', 467, 'Drama', 2008);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Swan Princess, The', 468, 'Animation|Children', 2007);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Billy Budd', 469, 'Adventure', 1998);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Texas Across the River', 470, 'Comedy|Western', 2006);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Secret Admirer', 471, 'Comedy|Romance', 1992);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('I Love You, Man', 472, 'Comedy', 2010);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Stake Land', 473, 'Horror', 1989);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('File on Thelma Jordan, The', 474, 'Crime|Drama|Film-Noir|Mystery', 1995);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Thankskilling', 475, 'Comedy|Horror', 1994);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Red Pony, The', 476, 'Drama', 1985);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Rage: Carrie 2, The', 477, 'Horror', 1993);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Wild Thornberrys Movie, The', 478, 'Animation|Children|Comedy', 2000);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Mille bolle blu', 479, 'Comedy', 2009);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Memoirs of a Geisha', 480, 'Drama|Romance', 1998);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Man of La Mancha', 481, 'Adventure|Comedy|Musical', 2009);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Santa Fe Trail', 482, 'Drama|Romance|Western', 1994);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Harmful Insect (Gaichu)', 483, 'Drama', 1997);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Taste of Others, The (Le goût des autres)', 484, 'Comedy|Drama|Romance', 1999);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Pusher II: With Blood on My Hands', 485, 'Action|Crime|Drama|Thriller', 1996);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Dragon Day', 486, 'Drama|Sci-Fi|Thriller', 2006);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Vivien Leigh: Scarlett and Beyond', 487, 'Documentary', 2003);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Interrupters, The', 488, 'Documentary', 2001);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Snow White', 489, 'Fantasy|Romance', 1989);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Dying Swan, The (Umirayushchii lebed)', 490, 'Drama', 1995);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Selena', 491, 'Drama|Musical', 1991);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Outside Ozona', 492, 'Comedy|Drama|Thriller', 1985);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Omen, The', 493, 'Horror|Thriller', 2004);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Not Your Typical Bigfoot Movie', 494, 'Documentary', 2011);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Orphans of the Storm', 495, 'Drama', 1993);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('They Live', 496, 'Action|Sci-Fi|Thriller', 2005);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Love Is Colder Than Death (Liebe ist kälter als der Tod)', 497, 'Comedy|Crime|Romance', 2008);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('House on Telegraph Hill, The', 498, 'Drama|Film-Noir|Mystery|Thriller', 1993);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('September Issue, The', 499, 'Documentary', 1991);
insert into Books (Title, AuthorID, Genre, PublishedYear) values ('Separation City', 500, 'Comedy|Drama|Romance', 1998);
